### ISSUE TITLE
400 Bad Request: {"error":"invalid_grant"}

### ISSUE THREAD

**Issue by MikeShap** [polarofficial/accesslink-example-python#10]
I saw that this problem was presented a few month ago and you deleted a line to solve it. 
However, in my case bringing back the line that was deleted actually solved the problem.

**Comment by vmhirvinen** [comment]
redirect_uri is required in token endpoint if redirect_uri is passed to authorization endpoint https://flow.polar.com/oauth2/authorization?response_type=code&scope={SCOPE}&client_id={CLIENT_ID}&state={STATE}

See token endpoint documentation at https://www.polar.com/accesslink-api/#token-endpoint: 

`redirect_uri: Must be specified if redirect_uri was passed to authorization endpoint`

**Comment by ssj2son-gohan-ne** [comment]
got the same error and adding the line
`"redirect_uri" : self.redirect_url,`
to oauth2.py (line 55) solved the problem

error:

```
python3 authorization.py
/home/gohan/goldencheetah-git/accesslink-example-python/utils.py:10: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(f)
Navigate to http://localhost:5000/ for authorization.

 * Serving Flask app "authorization" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [21/Mar/2020 09:51:14] "GET / HTTP/1.1" 302 -
[2020-03-21 09:51:21,498] ERROR in app: Exception on /oauth2_callback [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "authorization.py", line 51, in callback
    token_response = accesslink.get_access_token(authorization_code)
  File "/home/gohan/goldencheetah-git/accesslink-example-python/accesslink/accesslink.py", line 41, in get_access_token
    return self.oauth.get_access_token(authorization_code)
  File "/home/gohan/goldencheetah-git/accesslink-example-python/accesslink/oauth2.py", line 63, in get_access_token
    headers=headers)
  File "/home/gohan/goldencheetah-git/accesslink-example-python/accesslink/oauth2.py", line 128, in post
    return self.__request("post", endpoint=endpoint, **kwargs)
  File "/home/gohan/goldencheetah-git/accesslink-example-python/accesslink/oauth2.py", line 122, in __request
    return self.__parse_response(response)
  File "/home/gohan/goldencheetah-git/accesslink-example-python/accesslink/oauth2.py", line 109, in __parse_response
    raise HTTPError(message, response=response)
requests.exceptions.HTTPError: 400 Bad Request: {"error":"invalid_grant"}
127.0.0.1 - - [21/Mar/2020 09:51:21] "GET /oauth2_callback?code=6b9172348c3c8d44f9ae4f3d55e18ca3 HTTP/1.1" 500 -
```
